# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('cashier', 'Cashier'), ('stock', 'Stock Manager')], default='owner', max_length=100),
        ),
    ]
