# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_menu', to='restaurant_menu.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
