# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_purchasemenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemenuitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
