# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0004_auto_20180906_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemenuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
