# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0005_purchasemenuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
