# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0006_auto_20180907_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_menu', to='restaurant_menu.Category'),
        ),
        migrations.AlterField(
            model_name='purchasemenuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_menu', to='restaurant_menu.Menu'),
        ),
    ]
