# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockin', to='restaurant_stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockout', to='restaurant_stocks.Stock'),
        ),
    ]
