# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0002_auto_20180914_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('closed_stock_in', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_stock_out', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_stock_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('remaining_stock', models.CharField(blank=True, help_text='Difference of Stock In and Stock Out', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItemClosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_stock_in', models.CharField(blank=True, max_length=100, null=True)),
                ('item_stock_out', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_stock_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('remaining_stock_item', models.CharField(blank=True, help_text='Difference of Item Stock In and Item Stock Out', max_length=100, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item_closed', to='restaurant_stocks.Stock')),
                ('stock_closed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_closed', to='restaurant_stocks.StockClosed')),
            ],
        ),
    ]
