# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0004_stockin_closed_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockout',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
    ]
