# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0005_auto_20180926_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
