# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0007_auto_20180926_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('cnic', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCreditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('credit_ammount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
