# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0008_employee_employeecreditrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeCreditRecord',
        ),
    ]
