# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0009_auto_20181116_1807'),
        ('restaurant_stocks', '0008_auto_20190125_1707'),
    ]

    operations = [
    ]
