# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stocks', '0010_merge_20190125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
