# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_menu', '0002_purchasemenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_qty', models.IntegerField(max_length=3, verbose_name='Total Quantity')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('items', models.ManyToManyField(max_length=100, to='restaurant_menu.PurchaseMenuItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table_no', models.IntegerField(max_length=3, verbose_name='Table No.')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('table_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='restaurant_sales.Table'),
        ),
    ]
