# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.IntegerField(default=1, verbose_name='Total Quantity'),
        ),
    ]
