# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0002_auto_20180905_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_no',
            field=models.IntegerField(verbose_name='Table No.'),
        ),
    ]
