# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0003_auto_20180905_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_no',
            field=models.IntegerField(unique=True, verbose_name='Table No.'),
        ),
    ]
