# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0005_auto_20180905_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='restaurant_sales.Table'),
        ),
    ]
