# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0008_auto_20180905_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='table',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='total_due',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='total_qty',
        ),
    ]
