# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0011_remove_order2_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order2',
            name='total_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order2',
            name='total_qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Quantity'),
        ),
    ]
