# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0003_auto_20180905_1253'),
        ('restaurant_sales', '0012_auto_20180905_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='items',
            field=models.ManyToManyField(max_length=100, related_name='purchase_orders2', to='restaurant_menu.PurchaseMenuItem'),
        ),
    ]
