# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0014_order2_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='table',
        ),
    ]
