# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0015_remove_order2_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order2_table', to='restaurant_sales.Table'),
            preserve_default=False,
        ),
    ]
