# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0019_auto_20180914_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charges_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=7, max_digits=20, null=True),
        ),
    ]
