# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_sales', '0021_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
